apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy
  template:
    metadata:
      labels:
        app: policy
    spec:
      containers:
      - name: policy
        image: policy:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: MONGO_URI
          value: "mongodb://mongo:27017"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
