apiVersion: v1
kind: Service
metadata:
  name: policy
spec:
  type: ClusterIP
  selector:
    app: policy
  ports:
    - port: 9090     # healthcheck
      targetPort: 9090
      protocol: TCP
      name: http