version: '3.7'

services:
  mongo:
    image: sha256:ab6556e6d71d9773dd74002db924dc637abb49d079d6ef945982af3078fdf22c
    container_name: mongo
    environment:
      MONGO_INITDB_REPLICA_SET: rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    command: ["mongod", "--replSet", "rs0"]

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
