version: '3.8'

services:
  mongo:
    image: sha256:ab6556e6d71d9773dd74002db924dc637abb49d079d6ef945982af3078fdf22c
    container_name: mongo
    environment:
      MONGO_INITDB_REPLICA_SET: rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    command: ["mongod", "--replSet", "rs0"]

  ldap-server:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "Test Org"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    networks:
      - backend

  ldap-ui:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap-ui
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
