global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # - job_name: 'account'
  #   static_configs:
  #     - targets: ['account:8080']  # хост/порт Account сервиса

  # # можно добавить другие сервисы
