apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-external
  labels:
    app: kafka-ui
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30082