apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: account:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: MONGO_URI
          value: "mongodb://mongo:27017"