apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  type: ClusterIP
  selector:
    app: account
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http