apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-ui
  labels:
    app: ldap-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-ui
  template:
    metadata:
      labels:
        app: ldap-ui
    spec:
      containers:
      - name: ldap-ui
        image: osixia/phpldapadmin:0.9.0
        ports:
        - containerPort: 80
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: "ldap"
        - name: PHPLDAPADMIN_HTTPS
          value: "false"